
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PublicKey` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PublicKey
 * 
 */
export type PublicKeyModel = runtime.Types.Result.DefaultSelection<Prisma.$PublicKeyPayload>

export type AggregatePublicKey = {
  _count: PublicKeyCountAggregateOutputType | null
  _min: PublicKeyMinAggregateOutputType | null
  _max: PublicKeyMaxAggregateOutputType | null
}

export type PublicKeyMinAggregateOutputType = {
  id: string | null
  deviceId: string | null
  keyType: string | null
  publicKey: string | null
  createdAt: Date | null
  revokedAt: Date | null
}

export type PublicKeyMaxAggregateOutputType = {
  id: string | null
  deviceId: string | null
  keyType: string | null
  publicKey: string | null
  createdAt: Date | null
  revokedAt: Date | null
}

export type PublicKeyCountAggregateOutputType = {
  id: number
  deviceId: number
  keyType: number
  publicKey: number
  createdAt: number
  revokedAt: number
  _all: number
}


export type PublicKeyMinAggregateInputType = {
  id?: true
  deviceId?: true
  keyType?: true
  publicKey?: true
  createdAt?: true
  revokedAt?: true
}

export type PublicKeyMaxAggregateInputType = {
  id?: true
  deviceId?: true
  keyType?: true
  publicKey?: true
  createdAt?: true
  revokedAt?: true
}

export type PublicKeyCountAggregateInputType = {
  id?: true
  deviceId?: true
  keyType?: true
  publicKey?: true
  createdAt?: true
  revokedAt?: true
  _all?: true
}

export type PublicKeyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PublicKey to aggregate.
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublicKeys to fetch.
   */
  orderBy?: Prisma.PublicKeyOrderByWithRelationInput | Prisma.PublicKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PublicKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublicKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublicKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PublicKeys
  **/
  _count?: true | PublicKeyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PublicKeyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PublicKeyMaxAggregateInputType
}

export type GetPublicKeyAggregateType<T extends PublicKeyAggregateArgs> = {
      [P in keyof T & keyof AggregatePublicKey]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePublicKey[P]>
    : Prisma.GetScalarType<T[P], AggregatePublicKey[P]>
}




export type PublicKeyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PublicKeyWhereInput
  orderBy?: Prisma.PublicKeyOrderByWithAggregationInput | Prisma.PublicKeyOrderByWithAggregationInput[]
  by: Prisma.PublicKeyScalarFieldEnum[] | Prisma.PublicKeyScalarFieldEnum
  having?: Prisma.PublicKeyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PublicKeyCountAggregateInputType | true
  _min?: PublicKeyMinAggregateInputType
  _max?: PublicKeyMaxAggregateInputType
}

export type PublicKeyGroupByOutputType = {
  id: string
  deviceId: string
  keyType: string
  publicKey: string
  createdAt: Date
  revokedAt: Date | null
  _count: PublicKeyCountAggregateOutputType | null
  _min: PublicKeyMinAggregateOutputType | null
  _max: PublicKeyMaxAggregateOutputType | null
}

type GetPublicKeyGroupByPayload<T extends PublicKeyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PublicKeyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PublicKeyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PublicKeyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PublicKeyGroupByOutputType[P]>
      }
    >
  >



export type PublicKeyWhereInput = {
  AND?: Prisma.PublicKeyWhereInput | Prisma.PublicKeyWhereInput[]
  OR?: Prisma.PublicKeyWhereInput[]
  NOT?: Prisma.PublicKeyWhereInput | Prisma.PublicKeyWhereInput[]
  id?: Prisma.StringFilter<"PublicKey"> | string
  deviceId?: Prisma.StringFilter<"PublicKey"> | string
  keyType?: Prisma.StringFilter<"PublicKey"> | string
  publicKey?: Prisma.StringFilter<"PublicKey"> | string
  createdAt?: Prisma.DateTimeFilter<"PublicKey"> | Date | string
  revokedAt?: Prisma.DateTimeNullableFilter<"PublicKey"> | Date | string | null
  device?: Prisma.XOR<Prisma.DeviceScalarRelationFilter, Prisma.DeviceWhereInput>
}

export type PublicKeyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  keyType?: Prisma.SortOrder
  publicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  device?: Prisma.DeviceOrderByWithRelationInput
}

export type PublicKeyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PublicKeyWhereInput | Prisma.PublicKeyWhereInput[]
  OR?: Prisma.PublicKeyWhereInput[]
  NOT?: Prisma.PublicKeyWhereInput | Prisma.PublicKeyWhereInput[]
  deviceId?: Prisma.StringFilter<"PublicKey"> | string
  keyType?: Prisma.StringFilter<"PublicKey"> | string
  publicKey?: Prisma.StringFilter<"PublicKey"> | string
  createdAt?: Prisma.DateTimeFilter<"PublicKey"> | Date | string
  revokedAt?: Prisma.DateTimeNullableFilter<"PublicKey"> | Date | string | null
  device?: Prisma.XOR<Prisma.DeviceScalarRelationFilter, Prisma.DeviceWhereInput>
}, "id">

export type PublicKeyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  keyType?: Prisma.SortOrder
  publicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PublicKeyCountOrderByAggregateInput
  _max?: Prisma.PublicKeyMaxOrderByAggregateInput
  _min?: Prisma.PublicKeyMinOrderByAggregateInput
}

export type PublicKeyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PublicKeyScalarWhereWithAggregatesInput | Prisma.PublicKeyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PublicKeyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PublicKeyScalarWhereWithAggregatesInput | Prisma.PublicKeyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PublicKey"> | string
  deviceId?: Prisma.StringWithAggregatesFilter<"PublicKey"> | string
  keyType?: Prisma.StringWithAggregatesFilter<"PublicKey"> | string
  publicKey?: Prisma.StringWithAggregatesFilter<"PublicKey"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PublicKey"> | Date | string
  revokedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PublicKey"> | Date | string | null
}

export type PublicKeyCreateInput = {
  id?: string
  keyType: string
  publicKey: string
  createdAt?: Date | string
  revokedAt?: Date | string | null
  device: Prisma.DeviceCreateNestedOneWithoutPublicKeysInput
}

export type PublicKeyUncheckedCreateInput = {
  id?: string
  deviceId: string
  keyType: string
  publicKey: string
  createdAt?: Date | string
  revokedAt?: Date | string | null
}

export type PublicKeyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  device?: Prisma.DeviceUpdateOneRequiredWithoutPublicKeysNestedInput
}

export type PublicKeyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceId?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PublicKeyCreateManyInput = {
  id?: string
  deviceId: string
  keyType: string
  publicKey: string
  createdAt?: Date | string
  revokedAt?: Date | string | null
}

export type PublicKeyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PublicKeyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceId?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PublicKeyListRelationFilter = {
  every?: Prisma.PublicKeyWhereInput
  some?: Prisma.PublicKeyWhereInput
  none?: Prisma.PublicKeyWhereInput
}

export type PublicKeyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PublicKeyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  keyType?: Prisma.SortOrder
  publicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrder
}

export type PublicKeyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  keyType?: Prisma.SortOrder
  publicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrder
}

export type PublicKeyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  keyType?: Prisma.SortOrder
  publicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrder
}

export type PublicKeyCreateNestedManyWithoutDeviceInput = {
  create?: Prisma.XOR<Prisma.PublicKeyCreateWithoutDeviceInput, Prisma.PublicKeyUncheckedCreateWithoutDeviceInput> | Prisma.PublicKeyCreateWithoutDeviceInput[] | Prisma.PublicKeyUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.PublicKeyCreateOrConnectWithoutDeviceInput | Prisma.PublicKeyCreateOrConnectWithoutDeviceInput[]
  createMany?: Prisma.PublicKeyCreateManyDeviceInputEnvelope
  connect?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
}

export type PublicKeyUncheckedCreateNestedManyWithoutDeviceInput = {
  create?: Prisma.XOR<Prisma.PublicKeyCreateWithoutDeviceInput, Prisma.PublicKeyUncheckedCreateWithoutDeviceInput> | Prisma.PublicKeyCreateWithoutDeviceInput[] | Prisma.PublicKeyUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.PublicKeyCreateOrConnectWithoutDeviceInput | Prisma.PublicKeyCreateOrConnectWithoutDeviceInput[]
  createMany?: Prisma.PublicKeyCreateManyDeviceInputEnvelope
  connect?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
}

export type PublicKeyUpdateManyWithoutDeviceNestedInput = {
  create?: Prisma.XOR<Prisma.PublicKeyCreateWithoutDeviceInput, Prisma.PublicKeyUncheckedCreateWithoutDeviceInput> | Prisma.PublicKeyCreateWithoutDeviceInput[] | Prisma.PublicKeyUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.PublicKeyCreateOrConnectWithoutDeviceInput | Prisma.PublicKeyCreateOrConnectWithoutDeviceInput[]
  upsert?: Prisma.PublicKeyUpsertWithWhereUniqueWithoutDeviceInput | Prisma.PublicKeyUpsertWithWhereUniqueWithoutDeviceInput[]
  createMany?: Prisma.PublicKeyCreateManyDeviceInputEnvelope
  set?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  disconnect?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  delete?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  connect?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  update?: Prisma.PublicKeyUpdateWithWhereUniqueWithoutDeviceInput | Prisma.PublicKeyUpdateWithWhereUniqueWithoutDeviceInput[]
  updateMany?: Prisma.PublicKeyUpdateManyWithWhereWithoutDeviceInput | Prisma.PublicKeyUpdateManyWithWhereWithoutDeviceInput[]
  deleteMany?: Prisma.PublicKeyScalarWhereInput | Prisma.PublicKeyScalarWhereInput[]
}

export type PublicKeyUncheckedUpdateManyWithoutDeviceNestedInput = {
  create?: Prisma.XOR<Prisma.PublicKeyCreateWithoutDeviceInput, Prisma.PublicKeyUncheckedCreateWithoutDeviceInput> | Prisma.PublicKeyCreateWithoutDeviceInput[] | Prisma.PublicKeyUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.PublicKeyCreateOrConnectWithoutDeviceInput | Prisma.PublicKeyCreateOrConnectWithoutDeviceInput[]
  upsert?: Prisma.PublicKeyUpsertWithWhereUniqueWithoutDeviceInput | Prisma.PublicKeyUpsertWithWhereUniqueWithoutDeviceInput[]
  createMany?: Prisma.PublicKeyCreateManyDeviceInputEnvelope
  set?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  disconnect?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  delete?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  connect?: Prisma.PublicKeyWhereUniqueInput | Prisma.PublicKeyWhereUniqueInput[]
  update?: Prisma.PublicKeyUpdateWithWhereUniqueWithoutDeviceInput | Prisma.PublicKeyUpdateWithWhereUniqueWithoutDeviceInput[]
  updateMany?: Prisma.PublicKeyUpdateManyWithWhereWithoutDeviceInput | Prisma.PublicKeyUpdateManyWithWhereWithoutDeviceInput[]
  deleteMany?: Prisma.PublicKeyScalarWhereInput | Prisma.PublicKeyScalarWhereInput[]
}

export type PublicKeyCreateWithoutDeviceInput = {
  id?: string
  keyType: string
  publicKey: string
  createdAt?: Date | string
  revokedAt?: Date | string | null
}

export type PublicKeyUncheckedCreateWithoutDeviceInput = {
  id?: string
  keyType: string
  publicKey: string
  createdAt?: Date | string
  revokedAt?: Date | string | null
}

export type PublicKeyCreateOrConnectWithoutDeviceInput = {
  where: Prisma.PublicKeyWhereUniqueInput
  create: Prisma.XOR<Prisma.PublicKeyCreateWithoutDeviceInput, Prisma.PublicKeyUncheckedCreateWithoutDeviceInput>
}

export type PublicKeyCreateManyDeviceInputEnvelope = {
  data: Prisma.PublicKeyCreateManyDeviceInput | Prisma.PublicKeyCreateManyDeviceInput[]
  skipDuplicates?: boolean
}

export type PublicKeyUpsertWithWhereUniqueWithoutDeviceInput = {
  where: Prisma.PublicKeyWhereUniqueInput
  update: Prisma.XOR<Prisma.PublicKeyUpdateWithoutDeviceInput, Prisma.PublicKeyUncheckedUpdateWithoutDeviceInput>
  create: Prisma.XOR<Prisma.PublicKeyCreateWithoutDeviceInput, Prisma.PublicKeyUncheckedCreateWithoutDeviceInput>
}

export type PublicKeyUpdateWithWhereUniqueWithoutDeviceInput = {
  where: Prisma.PublicKeyWhereUniqueInput
  data: Prisma.XOR<Prisma.PublicKeyUpdateWithoutDeviceInput, Prisma.PublicKeyUncheckedUpdateWithoutDeviceInput>
}

export type PublicKeyUpdateManyWithWhereWithoutDeviceInput = {
  where: Prisma.PublicKeyScalarWhereInput
  data: Prisma.XOR<Prisma.PublicKeyUpdateManyMutationInput, Prisma.PublicKeyUncheckedUpdateManyWithoutDeviceInput>
}

export type PublicKeyScalarWhereInput = {
  AND?: Prisma.PublicKeyScalarWhereInput | Prisma.PublicKeyScalarWhereInput[]
  OR?: Prisma.PublicKeyScalarWhereInput[]
  NOT?: Prisma.PublicKeyScalarWhereInput | Prisma.PublicKeyScalarWhereInput[]
  id?: Prisma.StringFilter<"PublicKey"> | string
  deviceId?: Prisma.StringFilter<"PublicKey"> | string
  keyType?: Prisma.StringFilter<"PublicKey"> | string
  publicKey?: Prisma.StringFilter<"PublicKey"> | string
  createdAt?: Prisma.DateTimeFilter<"PublicKey"> | Date | string
  revokedAt?: Prisma.DateTimeNullableFilter<"PublicKey"> | Date | string | null
}

export type PublicKeyCreateManyDeviceInput = {
  id?: string
  keyType: string
  publicKey: string
  createdAt?: Date | string
  revokedAt?: Date | string | null
}

export type PublicKeyUpdateWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PublicKeyUncheckedUpdateWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PublicKeyUncheckedUpdateManyWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  keyType?: Prisma.StringFieldUpdateOperationsInput | string
  publicKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type PublicKeySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  deviceId?: boolean
  keyType?: boolean
  publicKey?: boolean
  createdAt?: boolean
  revokedAt?: boolean
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["publicKey"]>

export type PublicKeySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  deviceId?: boolean
  keyType?: boolean
  publicKey?: boolean
  createdAt?: boolean
  revokedAt?: boolean
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["publicKey"]>

export type PublicKeySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  deviceId?: boolean
  keyType?: boolean
  publicKey?: boolean
  createdAt?: boolean
  revokedAt?: boolean
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["publicKey"]>

export type PublicKeySelectScalar = {
  id?: boolean
  deviceId?: boolean
  keyType?: boolean
  publicKey?: boolean
  createdAt?: boolean
  revokedAt?: boolean
}

export type PublicKeyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "deviceId" | "keyType" | "publicKey" | "createdAt" | "revokedAt", ExtArgs["result"]["publicKey"]>
export type PublicKeyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}
export type PublicKeyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}
export type PublicKeyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}

export type $PublicKeyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PublicKey"
  objects: {
    device: Prisma.$DevicePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    deviceId: string
    keyType: string
    publicKey: string
    createdAt: Date
    revokedAt: Date | null
  }, ExtArgs["result"]["publicKey"]>
  composites: {}
}

export type PublicKeyGetPayload<S extends boolean | null | undefined | PublicKeyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload, S>

export type PublicKeyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PublicKeyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PublicKeyCountAggregateInputType | true
  }

export interface PublicKeyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PublicKey'], meta: { name: 'PublicKey' } }
  /**
   * Find zero or one PublicKey that matches the filter.
   * @param {PublicKeyFindUniqueArgs} args - Arguments to find a PublicKey
   * @example
   * // Get one PublicKey
   * const publicKey = await prisma.publicKey.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PublicKeyFindUniqueArgs>(args: Prisma.SelectSubset<T, PublicKeyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PublicKey that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PublicKeyFindUniqueOrThrowArgs} args - Arguments to find a PublicKey
   * @example
   * // Get one PublicKey
   * const publicKey = await prisma.publicKey.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PublicKeyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PublicKeyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PublicKey that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyFindFirstArgs} args - Arguments to find a PublicKey
   * @example
   * // Get one PublicKey
   * const publicKey = await prisma.publicKey.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PublicKeyFindFirstArgs>(args?: Prisma.SelectSubset<T, PublicKeyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PublicKey that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyFindFirstOrThrowArgs} args - Arguments to find a PublicKey
   * @example
   * // Get one PublicKey
   * const publicKey = await prisma.publicKey.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PublicKeyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PublicKeyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PublicKeys that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PublicKeys
   * const publicKeys = await prisma.publicKey.findMany()
   * 
   * // Get first 10 PublicKeys
   * const publicKeys = await prisma.publicKey.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const publicKeyWithIdOnly = await prisma.publicKey.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PublicKeyFindManyArgs>(args?: Prisma.SelectSubset<T, PublicKeyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PublicKey.
   * @param {PublicKeyCreateArgs} args - Arguments to create a PublicKey.
   * @example
   * // Create one PublicKey
   * const PublicKey = await prisma.publicKey.create({
   *   data: {
   *     // ... data to create a PublicKey
   *   }
   * })
   * 
   */
  create<T extends PublicKeyCreateArgs>(args: Prisma.SelectSubset<T, PublicKeyCreateArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PublicKeys.
   * @param {PublicKeyCreateManyArgs} args - Arguments to create many PublicKeys.
   * @example
   * // Create many PublicKeys
   * const publicKey = await prisma.publicKey.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PublicKeyCreateManyArgs>(args?: Prisma.SelectSubset<T, PublicKeyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PublicKeys and returns the data saved in the database.
   * @param {PublicKeyCreateManyAndReturnArgs} args - Arguments to create many PublicKeys.
   * @example
   * // Create many PublicKeys
   * const publicKey = await prisma.publicKey.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PublicKeys and only return the `id`
   * const publicKeyWithIdOnly = await prisma.publicKey.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PublicKeyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PublicKeyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PublicKey.
   * @param {PublicKeyDeleteArgs} args - Arguments to delete one PublicKey.
   * @example
   * // Delete one PublicKey
   * const PublicKey = await prisma.publicKey.delete({
   *   where: {
   *     // ... filter to delete one PublicKey
   *   }
   * })
   * 
   */
  delete<T extends PublicKeyDeleteArgs>(args: Prisma.SelectSubset<T, PublicKeyDeleteArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PublicKey.
   * @param {PublicKeyUpdateArgs} args - Arguments to update one PublicKey.
   * @example
   * // Update one PublicKey
   * const publicKey = await prisma.publicKey.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PublicKeyUpdateArgs>(args: Prisma.SelectSubset<T, PublicKeyUpdateArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PublicKeys.
   * @param {PublicKeyDeleteManyArgs} args - Arguments to filter PublicKeys to delete.
   * @example
   * // Delete a few PublicKeys
   * const { count } = await prisma.publicKey.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PublicKeyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PublicKeyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PublicKeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PublicKeys
   * const publicKey = await prisma.publicKey.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PublicKeyUpdateManyArgs>(args: Prisma.SelectSubset<T, PublicKeyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PublicKeys and returns the data updated in the database.
   * @param {PublicKeyUpdateManyAndReturnArgs} args - Arguments to update many PublicKeys.
   * @example
   * // Update many PublicKeys
   * const publicKey = await prisma.publicKey.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PublicKeys and only return the `id`
   * const publicKeyWithIdOnly = await prisma.publicKey.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PublicKeyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PublicKeyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PublicKey.
   * @param {PublicKeyUpsertArgs} args - Arguments to update or create a PublicKey.
   * @example
   * // Update or create a PublicKey
   * const publicKey = await prisma.publicKey.upsert({
   *   create: {
   *     // ... data to create a PublicKey
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PublicKey we want to update
   *   }
   * })
   */
  upsert<T extends PublicKeyUpsertArgs>(args: Prisma.SelectSubset<T, PublicKeyUpsertArgs<ExtArgs>>): Prisma.Prisma__PublicKeyClient<runtime.Types.Result.GetResult<Prisma.$PublicKeyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PublicKeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyCountArgs} args - Arguments to filter PublicKeys to count.
   * @example
   * // Count the number of PublicKeys
   * const count = await prisma.publicKey.count({
   *   where: {
   *     // ... the filter for the PublicKeys we want to count
   *   }
   * })
  **/
  count<T extends PublicKeyCountArgs>(
    args?: Prisma.Subset<T, PublicKeyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PublicKeyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PublicKey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PublicKeyAggregateArgs>(args: Prisma.Subset<T, PublicKeyAggregateArgs>): Prisma.PrismaPromise<GetPublicKeyAggregateType<T>>

  /**
   * Group by PublicKey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublicKeyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PublicKeyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PublicKeyGroupByArgs['orderBy'] }
      : { orderBy?: PublicKeyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PublicKeyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPublicKeyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PublicKey model
 */
readonly fields: PublicKeyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PublicKey.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PublicKeyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  device<T extends Prisma.DeviceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeviceDefaultArgs<ExtArgs>>): Prisma.Prisma__DeviceClient<runtime.Types.Result.GetResult<Prisma.$DevicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PublicKey model
 */
export interface PublicKeyFieldRefs {
  readonly id: Prisma.FieldRef<"PublicKey", 'String'>
  readonly deviceId: Prisma.FieldRef<"PublicKey", 'String'>
  readonly keyType: Prisma.FieldRef<"PublicKey", 'String'>
  readonly publicKey: Prisma.FieldRef<"PublicKey", 'String'>
  readonly createdAt: Prisma.FieldRef<"PublicKey", 'DateTime'>
  readonly revokedAt: Prisma.FieldRef<"PublicKey", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PublicKey findUnique
 */
export type PublicKeyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * Filter, which PublicKey to fetch.
   */
  where: Prisma.PublicKeyWhereUniqueInput
}

/**
 * PublicKey findUniqueOrThrow
 */
export type PublicKeyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * Filter, which PublicKey to fetch.
   */
  where: Prisma.PublicKeyWhereUniqueInput
}

/**
 * PublicKey findFirst
 */
export type PublicKeyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * Filter, which PublicKey to fetch.
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublicKeys to fetch.
   */
  orderBy?: Prisma.PublicKeyOrderByWithRelationInput | Prisma.PublicKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PublicKeys.
   */
  cursor?: Prisma.PublicKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublicKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublicKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PublicKeys.
   */
  distinct?: Prisma.PublicKeyScalarFieldEnum | Prisma.PublicKeyScalarFieldEnum[]
}

/**
 * PublicKey findFirstOrThrow
 */
export type PublicKeyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * Filter, which PublicKey to fetch.
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublicKeys to fetch.
   */
  orderBy?: Prisma.PublicKeyOrderByWithRelationInput | Prisma.PublicKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PublicKeys.
   */
  cursor?: Prisma.PublicKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublicKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublicKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PublicKeys.
   */
  distinct?: Prisma.PublicKeyScalarFieldEnum | Prisma.PublicKeyScalarFieldEnum[]
}

/**
 * PublicKey findMany
 */
export type PublicKeyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * Filter, which PublicKeys to fetch.
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublicKeys to fetch.
   */
  orderBy?: Prisma.PublicKeyOrderByWithRelationInput | Prisma.PublicKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PublicKeys.
   */
  cursor?: Prisma.PublicKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublicKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublicKeys.
   */
  skip?: number
  distinct?: Prisma.PublicKeyScalarFieldEnum | Prisma.PublicKeyScalarFieldEnum[]
}

/**
 * PublicKey create
 */
export type PublicKeyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * The data needed to create a PublicKey.
   */
  data: Prisma.XOR<Prisma.PublicKeyCreateInput, Prisma.PublicKeyUncheckedCreateInput>
}

/**
 * PublicKey createMany
 */
export type PublicKeyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PublicKeys.
   */
  data: Prisma.PublicKeyCreateManyInput | Prisma.PublicKeyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PublicKey createManyAndReturn
 */
export type PublicKeyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * The data used to create many PublicKeys.
   */
  data: Prisma.PublicKeyCreateManyInput | Prisma.PublicKeyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PublicKey update
 */
export type PublicKeyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * The data needed to update a PublicKey.
   */
  data: Prisma.XOR<Prisma.PublicKeyUpdateInput, Prisma.PublicKeyUncheckedUpdateInput>
  /**
   * Choose, which PublicKey to update.
   */
  where: Prisma.PublicKeyWhereUniqueInput
}

/**
 * PublicKey updateMany
 */
export type PublicKeyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PublicKeys.
   */
  data: Prisma.XOR<Prisma.PublicKeyUpdateManyMutationInput, Prisma.PublicKeyUncheckedUpdateManyInput>
  /**
   * Filter which PublicKeys to update
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * Limit how many PublicKeys to update.
   */
  limit?: number
}

/**
 * PublicKey updateManyAndReturn
 */
export type PublicKeyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * The data used to update PublicKeys.
   */
  data: Prisma.XOR<Prisma.PublicKeyUpdateManyMutationInput, Prisma.PublicKeyUncheckedUpdateManyInput>
  /**
   * Filter which PublicKeys to update
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * Limit how many PublicKeys to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PublicKey upsert
 */
export type PublicKeyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * The filter to search for the PublicKey to update in case it exists.
   */
  where: Prisma.PublicKeyWhereUniqueInput
  /**
   * In case the PublicKey found by the `where` argument doesn't exist, create a new PublicKey with this data.
   */
  create: Prisma.XOR<Prisma.PublicKeyCreateInput, Prisma.PublicKeyUncheckedCreateInput>
  /**
   * In case the PublicKey was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PublicKeyUpdateInput, Prisma.PublicKeyUncheckedUpdateInput>
}

/**
 * PublicKey delete
 */
export type PublicKeyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
  /**
   * Filter which PublicKey to delete.
   */
  where: Prisma.PublicKeyWhereUniqueInput
}

/**
 * PublicKey deleteMany
 */
export type PublicKeyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PublicKeys to delete
   */
  where?: Prisma.PublicKeyWhereInput
  /**
   * Limit how many PublicKeys to delete.
   */
  limit?: number
}

/**
 * PublicKey without action
 */
export type PublicKeyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublicKey
   */
  select?: Prisma.PublicKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublicKey
   */
  omit?: Prisma.PublicKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublicKeyInclude<ExtArgs> | null
}
